name: holo
description: null
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  motion_sensors:
    git: https://github.com/natsuk4ze/motion_sensors

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  uses-material-design: true
